# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageProccessor.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15imageProccessor.proto\x12\x0eimageProcessor\"\xc2\x01\n\x0cImageRequest\x12\x12\n\nbyte_image\x18\x01 \x01(\x0c\x12\x1a\n\x12\x61llowed_colors_str\x18\x02 \x03(\t\x12\x12\n\nbackground\x18\x03 \x01(\t\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x16\n\x0eresolution_pos\x18\x06 \x01(\t\x12\x0c\n\x04text\x18\x07 \x01(\t\x12\x0c\n\x04\x66ont\x18\x08 \x01(\t\x12\x1b\n\x13should_check_colors\x18\t \x01(\x08\"3\n\rImageResponse\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\\\n\x0eImageProcessor\x12J\n\x0bVerifyImage\x12\x1c.imageProcessor.ImageRequest\x1a\x1d.imageProcessor.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imageProccessor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=42
  _globals['_IMAGEREQUEST']._serialized_end=236
  _globals['_IMAGERESPONSE']._serialized_start=238
  _globals['_IMAGERESPONSE']._serialized_end=289
  _globals['_IMAGEPROCESSOR']._serialized_start=291
  _globals['_IMAGEPROCESSOR']._serialized_end=383
# @@protoc_insertion_point(module_scope)
