version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QWERTYUIO2313
      POSTGRES_DB: imageagregationdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data