##our S3 storage docker-compose.yml                                                                                   docker-compose.yml                                                                                            
services:
  s3:
    container_name: s3
    image: docker.io/minio/minio
    command: server /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=s3manager
      - MINIO_SECRET_KEY=s3manager
      - MINIO_ADDRESS=0.0.0.0:9000
      - MINIO_CONSOLE_ADDRESS=0.0.0.0:9001