# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageVerifier.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13imageVerifier.proto\x12\rimageverifier\"@\n\x12VerifyImageRequest\x12\x18\n\x10image_byte_array\x18\x01 \x01(\x0c\x12\x10\n\x08template\x18\x02 \x01(\t\">\n\x13VerifyImageResponse\x12\x18\n\x10image_byte_array\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2e\n\rImageVerifier\x12T\n\x0bVerifyImage\x12!.imageverifier.VerifyImageRequest\x1a\".imageverifier.VerifyImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imageVerifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYIMAGEREQUEST']._serialized_start=38
  _globals['_VERIFYIMAGEREQUEST']._serialized_end=102
  _globals['_VERIFYIMAGERESPONSE']._serialized_start=104
  _globals['_VERIFYIMAGERESPONSE']._serialized_end=166
  _globals['_IMAGEVERIFIER']._serialized_start=168
  _globals['_IMAGEVERIFIER']._serialized_end=269
# @@protoc_insertion_point(module_scope)
