# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageTextAdder.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14imageTextAdder.proto\x12\x0eimagetextadder\"?\n\x15\x41\x64\x64TextToImageRequest\x12\x18\n\x10image_byte_array\x18\x01 \x01(\x0c\x12\x0c\n\x04text\x18\x02 \x01(\t\"A\n\x16\x41\x64\x64TextToImageResponse\x12\x18\n\x10image_byte_array\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2q\n\x0eImageTextAdder\x12_\n\x0e\x41\x64\x64TextToImage\x12%.imagetextadder.AddTextToImageRequest\x1a&.imagetextadder.AddTextToImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imageTextAdder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDTEXTTOIMAGEREQUEST']._serialized_start=40
  _globals['_ADDTEXTTOIMAGEREQUEST']._serialized_end=103
  _globals['_ADDTEXTTOIMAGERESPONSE']._serialized_start=105
  _globals['_ADDTEXTTOIMAGERESPONSE']._serialized_end=170
  _globals['_IMAGETEXTADDER']._serialized_start=172
  _globals['_IMAGETEXTADDER']._serialized_end=285
# @@protoc_insertion_point(module_scope)
